import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

const root = process.cwd();
const read = (relative: string) => readFileSync(path.join(root, relative), 'utf8');

describe('custom native plugin integration', () => {
  it('declares matching Java and Swift bridge names', () => {
    const java = read('plugins/custom-native/android/src/main/java/dev/nativekit/custom/NativeKitCustomPlugin.java');
    const swift = read('plugins/custom-native/ios/Sources/NativeKitCustomPlugin/NativeKitCustomPlugin.swift');
    expect(java).toContain('@CapacitorPlugin(name = "NativeKitCustom")');
    expect(swift).toContain('public let jsName = "NativeKitCustom"');
  });

  it('exposes Android alarm and location components through manifest merging', () => {
    const manifest = read('plugins/custom-native/android/src/main/AndroidManifest.xml');
    for (const name of ['AlarmReceiver', 'AlarmService', 'BootReceiver', 'LocationTrackingService']) {
      expect(manifest).toContain(`dev.nativekit.custom.${name}`);
    }
  });

  it('uses the Swift product name expected by Capacitor package generation', () => {
    const pluginPackage = read('plugins/custom-native/Package.swift');
    const appPackage = read('ios/App/CapApp-SPM/Package.swift');
    expect(pluginPackage).toContain('name: "NativekitCustomNative"');
    expect(appPackage).toContain('.product(name: "NativekitCustomNative"');
  });

  it('gives AlarmKit attributes an explicit metadata type', () => {
    const alarm = read('plugins/custom-native/ios/Sources/NativeKitCustomPlugin/AlarmAdapter.swift');
    expect(alarm).toContain('struct NativeKitAlarmMetadata: AlarmMetadata');
    expect(alarm).toContain('AlarmAttributes<NativeKitAlarmMetadata>');
  });
});

describe('isolated renderer lifecycle hardening', () => {
  it('exports the Swift product name generated by Capacitor', () => {
    const pluginPackage = read('plugins/isolated-browser/Package.swift');
    const appPackage = read('ios/App/CapApp-SPM/Package.swift');
    expect(pluginPackage).toContain('.library(name: "NativekitIsolatedBrowser"');
    expect(appPackage).toContain(
      '.product(name: "NativekitIsolatedBrowser", package: "NativekitIsolatedBrowser")',
    );
  });

  it('chunks Android Messenger payloads and authenticates each renderer generation', () => {
    const service = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/IsolatedBrowserBrokerService.java');
    const activity = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/IsolatedBrowserActivity.java');
    expect(service).toContain('MAX_IPC_CHUNK_CHARS = 120_000');
    expect(service).toContain('MSG_REQUEST_CHUNK');
    expect(service).toContain('MSG_RESPONSE_CHUNK');
    expect(service).toContain('record.rendererToken');
    expect(service).toContain('record.clientBinder != expectedBinder');
    expect(activity).toContain('EXTRA_RENDERER_TOKEN');
    expect(activity).toContain('RPC_CHANNEL = "nativekit-app-browser-v1"');
    expect(activity).toContain('sendRequestChunks');
    expect(activity).toContain('acceptResponseChunk');
  });

  it('uses per-app WebView profiles when available and completion-aware deletion', () => {
    const activity = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/IsolatedBrowserActivity.java');
    const cleanup = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/IsolatedStorageCleanupService.java');
    const plugin = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/NativeKitIsolatedBrowserPlugin.java');
    expect(activity).toContain('WebViewCompat.setProfile');
    expect(cleanup).toContain('ProfileStore.getInstance().deleteProfile');
    expect(cleanup).toContain('WebStorageCompat.deleteBrowsingDataForSite');
    expect(plugin).toContain('ResultReceiver receiver');
  });

  it('replaces an unresponsive iOS content renderer without restarting the host', () => {
    const view = read('plugins/isolated-browser/ios/Sources/NativeKitIsolatedBrowserPlugin/IsolatedBrowserViewController.swift');
    expect(view).toContain('private func watchdogTick()');
    expect(view).toContain('private static let rpcChannel = "nativekit-app-browser-v1"');
    expect(view).toContain('WebKit content process missed the NativeKit heartbeat');
    expect(view).toContain('configuration.processPool = WKProcessPool()');
    expect(view).toContain('Reload isolated app');
    expect(view).not.toContain("script-src 'self' 'unsafe-inline' 'unsafe-eval'");
  });

  it('keeps local app capabilities while denying remote executable and framed content', () => {
    const activity = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/IsolatedBrowserActivity.java');
    const view = read('plugins/isolated-browser/ios/Sources/NativeKitIsolatedBrowserPlugin/IsolatedBrowserViewController.swift');
    const broker = read('bridge/app-browser.ts');
    for (const source of [activity, view]) {
      expect(source).toContain("script-src 'self' 'unsafe-inline' data: blob:");
      expect(source).toContain("worker-src 'self' blob:");
      expect(source).toContain("frame-src 'self' data: blob:");
      expect(source).toContain("form-action 'none'");
    }
    expect(activity).toContain("connect-src 'self'");
    expect(activity).toContain('wss.append(" wss://").append(host)');
    expect(view).toContain("connect-src 'self'");
    expect(view).toContain('allowedHosts.map { "wss://\\($0)" }');
    expect(broker).toContain('connect-src ${directSources}');
    expect(broker).toContain('frame-src data: blob:');
    expect(activity).not.toContain('frame-src" + https');
    expect(broker).not.toContain('frame-src ${approvedHttps}');
  });
});

describe('trusted call-time consent and bridge-free URL mode', () => {
  it('keeps four-action mini-app permission approval in trusted Android native UI and authenticated IPC', () => {
    const service = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/IsolatedBrowserBrokerService.java');
    const activity = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/IsolatedBrowserActivity.java');
    const plugin = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/NativeKitIsolatedBrowserPlugin.java');
    for (const action of ['allow_once', 'allow_always', 'block_once', 'block_always']) {
      expect(activity).toContain(action);
      expect(service).toContain(action);
    }
    expect(service).toContain('pendingPermissions');
    expect(service).toContain('rendererToken');
    expect(plugin).toContain('public void requestPermission(PluginCall call)');
    expect(plugin).toContain('public void dismissPermission(PluginCall call)');
  });

  it('keeps four-action mini-app permission approval in trusted iOS native UI', () => {
    const plugin = read('plugins/isolated-browser/ios/Sources/NativeKitIsolatedBrowserPlugin/NativeKitIsolatedBrowserPlugin.swift');
    for (const action of ['allow_once', 'allow_always', 'block_once', 'block_always']) expect(plugin).toContain(action);
    expect(plugin).toContain('pendingPermissions');
    expect(plugin).toContain('@objc func requestPermission');
    expect(plugin).toContain('@objc func dismissPermission');
    expect(plugin).toContain('UIAlertController');
  });

  it('implements Android remote HTTPS browsing without any JavaScript/native bridge', () => {
    const remote = read('plugins/isolated-browser/android/src/main/java/dev/nativekit/isolatedbrowser/RemoteBrowserActivity.java');
    expect(remote).toContain('"https".equalsIgnoreCase(uri.getScheme())');
    expect(remote).toContain('WebViewCompat.setProfile');
    expect(remote).toContain('setAcceptThirdPartyCookies(webView, false)');
    expect(remote).toContain('callback.invoke(origin, false, false)');
    expect(remote).not.toContain('addJavascriptInterface');
    expect(remote).not.toContain('addWebMessageListener');
    expect(remote).not.toContain('evaluateJavascript');
    expect(remote).not.toContain('nativekit-app-browser-v1');
  });

  it('implements iOS remote HTTPS browsing without scripts, message handlers, or capture access', () => {
    const remote = read('plugins/isolated-browser/ios/Sources/NativeKitIsolatedBrowserPlugin/RemoteBrowserViewController.swift');
    const store = read('plugins/isolated-browser/ios/Sources/NativeKitIsolatedBrowserPlugin/IsolatedAppStore.swift');
    expect(remote).toContain('WKWebsiteDataStore(forIdentifier: IsolatedAppStore.remoteProfileIdentifier)');
    expect(remote).toContain('configuration.websiteDataStore = .default()');
    expect(store).toContain('static let remoteProfileIdentifier');
    expect(remote).toContain('url.scheme?.lowercased() == "https"');
    expect(remote).toContain('decisionHandler(.deny)');
    expect(remote).toContain('@available(iOS 18.4, *)\n    func webView(_ webView: WKWebView, runOpenPanelWith');
    expect(remote).not.toContain('WKUserScript');
    expect(remote).not.toContain('addScriptMessageHandler');
    expect(remote).not.toContain('userContentController.add');
    expect(remote).not.toContain('nativekit-app-browser-v1');
  });

  it('exposes URL sessions as explicitly NativeKit-free and mutually excludes full-screen surfaces', () => {
    const broker = read('bridge/app-browser.ts');
    expect(broker).toContain("openUrl: async (input: string");
    expect(broker).toContain("mode: 'url', url: url.toString(), nativeKit: false");
    expect(broker).toContain("url.protocol !== 'https:'");
    expect(broker).toContain('for (const remote of Array.from(remoteUrlSessions.keys())) await stopRemoteUrl(remote)');
    expect(broker).toContain("NativeKitIsolatedBrowser.addListener('remoteBrowserStatus'");
  });

  it('wires the trusted manager to the actual permission events and structured audit error field', () => {
    const broker = read('bridge/app-browser.ts');
    const manager = read('www/app-browser-manager.js');
    const declarations = read('types/nativekit.d.ts.template');
    expect(broker).toContain("new CustomEvent('nativekitappbrowserpermissionrequest'");
    expect(manager).toContain("addEventListener('nativekitappbrowserpermissionrequest'");
    expect(manager).toContain("addEventListener('nativekitappbrowserpermissionresolved'");
    expect(declarations).toContain('nativekitappbrowserpermissionrequest: CustomEvent');
    expect(manager).toContain('item.errorCode ?? item.error');
    expect(manager).not.toContain("addEventListener('nativekitappbrowserpermission'");
  });
});
