#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { rootDir, resolveInsideRoot, validateConfig } from './config-lib.mjs';

const BRIDGE_MARKER = 'data-nativekit-bridge';
const SW_MARKER = 'data-nativekit-sw-register';

export function injectHeadAsset(html, tag, marker) {
  const oldTag = new RegExp(`<[^>]+${marker}[^>]*>(?:<\\/script>)?`, 'gi');
  const cleaned = html.replace(oldTag, '');
  const head = /<head(?:\s[^>]*)?>/i;
  if (head.test(cleaned)) return cleaned.replace(head, (match) => `${match}\n    ${tag}`);
  const htmlTag = /<html(?:\s[^>]*)?>/i;
  if (htmlTag.test(cleaned)) return cleaned.replace(htmlTag, (match) => `${match}\n  <head>\n    ${tag}\n  </head>`);
  return `<!doctype html>\n<html><head>${tag}</head><body>${cleaned}</body></html>`;
}

export function injectCsp(html, policy) {
  if (/http-equiv=["']Content-Security-Policy["']/i.test(html)) return html;
  const escaped = policy.replaceAll('&', '&amp;').replaceAll('"', '&quot;');
  return injectHeadAsset(
    html,
    `<meta http-equiv="Content-Security-Policy" content="${escaped}" data-nativekit-csp>`,
    'data-nativekit-csp',
  );
}

async function run(command, cwd) {
  await new Promise((resolve, reject) => {
    const child = spawn(command, { cwd, shell: true, stdio: 'inherit', env: process.env });
    child.once('error', reject);
    child.once('exit', (code, signal) => {
      if (code === 0) resolve();
      else reject(new Error(`Web build ব্যর্থ (exit=${code}, signal=${signal ?? 'none'}): ${command}`));
    });
  });
}

async function assertNoSymlinks(directory) {
  const entries = await fs.readdir(directory, { withFileTypes: true, recursive: true });
  const symlink = entries.find((entry) => entry.isSymbolicLink());
  if (symlink) throw new Error(`Web source-এ symlink অনুমোদিত নয়: ${symlink.name}`);
}

async function copyClean(source, destination) {
  const stat = await fs.stat(source).catch(() => null);
  if (!stat?.isDirectory()) throw new Error(`Web output directory পাওয়া যায়নি: ${path.relative(rootDir, source)}`);
  await assertNoSymlinks(source);
  await fs.rm(destination, { recursive: true, force: true });
  await fs.mkdir(path.dirname(destination), { recursive: true });
  await fs.cp(source, destination, {
    recursive: true,
    force: true,
    filter: (src) => !['node_modules', '.git', '.nativekit'].includes(path.basename(src)),
  });
}

async function listFiles(directory) {
  const result = [];
  async function walk(current) {
    for (const entry of await fs.readdir(current, { withFileTypes: true })) {
      const absolute = path.join(current, entry.name);
      if (entry.isDirectory()) await walk(absolute);
      else if (entry.isFile()) result.push(path.relative(directory, absolute).split(path.sep).join('/'));
    }
  }
  await walk(directory);
  return result.sort();
}

export async function contentRevision(directory, files) {
  const hash = createHash('sha256');
  for (const file of files) {
    hash.update(file);
    hash.update('\0');
    hash.update(await fs.readFile(path.join(directory, file)));
    hash.update('\0');
  }
  return hash.digest('hex').slice(0, 12);
}

function createServiceWorker(cacheName, files, fallback, revision) {
  const cache = `${cacheName}-${revision}`;
  const urls = files.filter((file) => !file.startsWith('nativekit-sw')).map((file) => `./${file}`);
  return `/* Generated by NativeKit. Web/PWA target only; this cannot bypass CORS. */
const CACHE = ${JSON.stringify(cache)};
const PRECACHE = ${JSON.stringify(urls, null, 2)};
const FALLBACK = ${JSON.stringify(`./${fallback}`)};
self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CACHE && key.startsWith(${JSON.stringify(cacheName)})).map((key) => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (event) => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).then((response) => {
      const copy = response.clone();
      caches.open(CACHE).then((cache) => cache.put(request, copy));
      return response;
    }).catch(() => caches.match(request).then((hit) => hit || caches.match(FALLBACK))));
    return;
  }
  event.respondWith(caches.match(request).then((hit) => hit || fetch(request).then((response) => {
    if (response.ok) caches.open(CACHE).then((cache) => cache.put(request, response.clone()));
    return response;
  })));
});
`;
}

async function main() {
  const targetArg = process.argv.find((item) => item.startsWith('--target='));
  const targetIndex = process.argv.indexOf('--target');
  const target = targetArg?.split('=')[1] ?? (targetIndex >= 0 ? process.argv[targetIndex + 1] : 'native');
  if (!['native', 'web'].includes(target)) throw new Error('--target native অথবা --target web হতে হবে');

  const { config, warnings } = await validateConfig();
  for (const warning of warnings) console.warn(`⚠ ${warning}`);

  let source;
  if (config.web.mode === 'framework') {
    const workDir = resolveInsideRoot(config.web.framework.workDir);
    console.log(`→ Framework build: ${config.web.framework.buildCommand}`);
    await run(config.web.framework.buildCommand, workDir);
    source = path.resolve(workDir, config.web.framework.outputDir);
    const rel = path.relative(rootDir, source);
    if (rel.startsWith('..') || path.isAbsolute(rel)) throw new Error('Framework output project root-এর ভিতরে হতে হবে');
  } else {
    source = resolveInsideRoot(config.web.staticDir);
  }

  const destination = resolveInsideRoot(target === 'native' ? config.web.nativeStagingDir : config.web.webOutputDir);
  if (path.resolve(source) === path.resolve(destination)) throw new Error('Source ও destination একই directory হতে পারবে না');
  await copyClean(source, destination);

  const indexPath = path.join(destination, 'index.html');
  let indexHtml = await fs.readFile(indexPath, 'utf8').catch(() => null);
  if (!indexHtml) throw new Error(`${path.relative(rootDir, source)}/index.html পাওয়া যায়নি`);
  if (!/<html[\s>]/i.test(indexHtml)) throw new Error('index.html-এ বৈধ <html> element নেই');

  if (config.web.injectBridge) {
    const bridgeScript = path.join(rootDir, 'scripts', 'build-bridge.mjs');
    await import(`${pathToFileURL(bridgeScript).href}?t=${Date.now()}`);
    await fs.copyFile(path.join(rootDir, '.nativekit', 'bridge', 'nativekit.js'), path.join(destination, 'nativekit.js'));
    indexHtml = injectHeadAsset(indexHtml, '<script src="./nativekit.js" data-nativekit-bridge></script>', BRIDGE_MARKER);
  }
  indexHtml = injectCsp(indexHtml, config.security.contentSecurityPolicy);

  if (target === 'web' && config.web.serviceWorker.enabledForWebTarget) {
    const register = `if ('serviceWorker' in navigator && (location.protocol === 'https:' || location.hostname === 'localhost' || location.hostname === '127.0.0.1')) {\n  addEventListener('load', () => navigator.serviceWorker.register('./nativekit-sw.js').catch((error) => console.warn('NativeKit SW registration failed', error)));\n}\n`;
    await fs.writeFile(path.join(destination, 'nativekit-sw-register.js'), register);
    indexHtml = injectHeadAsset(indexHtml, '<script defer src="./nativekit-sw-register.js" data-nativekit-sw-register></script>', SW_MARKER);
    await fs.writeFile(indexPath, indexHtml);
    const files = await listFiles(destination);
    const revision = await contentRevision(destination, files);
    const worker = createServiceWorker(config.web.serviceWorker.cacheName, files, config.web.serviceWorker.offlineFallback, revision);
    await fs.writeFile(path.join(destination, 'nativekit-sw.js'), worker);
  } else {
    indexHtml = indexHtml.replace(new RegExp(`<[^>]+${SW_MARKER}[^>]*>(?:<\\/script>)?`, 'gi'), '');
    await fs.rm(path.join(destination, 'nativekit-sw.js'), { force: true });
    await fs.rm(path.join(destination, 'nativekit-sw-register.js'), { force: true });
    await fs.writeFile(indexPath, indexHtml);
  }

  const files = await listFiles(destination);
  const hasUserServiceWorkerCode = /serviceWorker\s*\.\s*register\s*\(/.test(indexHtml) && !indexHtml.includes(SW_MARKER);
  if (target === 'native' && hasUserServiceWorkerCode) {
    console.warn('⚠ Native index.html-এ user-defined Service Worker registration দেখা গেছে; iOS local bundle-এ এটি নির্ভরযোগ্য নয়।');
  }
  console.log(`✓ ${target} web output প্রস্তুত: ${path.relative(rootDir, destination)} (${files.length} files)`);
}

const invokedDirectly = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname);
if (invokedDirectly) {
  main().catch((error) => {
    console.error(`✗ ${error.message}`);
    process.exitCode = 1;
  });
}
