package dev.nativekit.shell;

import dev.nativekit.widget.NativeKitWidgetProvider;

/** Generated by NativeKit for home-screen widget kind 'nativekit-widget'. */
public final class Widget_nativekit_widget extends NativeKitWidgetProvider {
    @Override public String kind() { return "nativekit-widget"; }
}
